[package]
name = "aruba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1"
cucumber = "0.16"
futures = "0.3"
lazy_static = "1.4"
pretty_assertions = "1"
regex = "1.6"
tempfile = "3"
